# Generated by Django 2.0.4 on 2018-04-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='which_time',
            field=models.IntegerField(default=1, verbose_name='第几次课'),
        ),
    ]
