# Generated by Django 2.0.4 on 2018-05-02 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuinfo',
            options={'verbose_name': '学生信息', 'verbose_name_plural': '学生信息'},
        ),
        migrations.AlterModelManagers(
            name='marketerinfo',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='marketerinfo',
            name='username',
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='duration',
            field=models.IntegerField(default=2, verbose_name='上课学时'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='referee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.MarketerInfo', verbose_name='招生人'),
        ),
    ]
