# Generated by Django 2.0.4 on 2018-04-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '开班列表', 'verbose_name_plural': '开班列表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程信息', 'verbose_name_plural': '课程信息'},
        ),
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'verbose_name': '学校列表', 'verbose_name_plural': '学校列表'},
        ),
        migrations.AlterField(
            model_name='classlist',
            name='notice',
            field=models.CharField(blank=True, max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='course',
            name='notice',
            field=models.CharField(blank=True, max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='marketerinfo',
            name='notice',
            field=models.CharField(blank=True, max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='notice',
            field=models.CharField(blank=True, max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='notice',
            field=models.CharField(blank=True, max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='notice',
            field=models.CharField(blank=True, max_length=128, verbose_name='备注'),
        ),
    ]
