# Generated by Django 2.0.4 on 2018-04-28 02:02

from django.db import migrations, models
import django.db.models.deletion
import internal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20180428_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='上课时间')),
                ('address', models.CharField(default='海悦天地', max_length=128, verbose_name='上课地点')),
                ('which_time', models.IntegerField(default=1, verbose_name='第几次课')),
                ('duration', models.IntegerField(default=2, verbose_name='上课学时')),
                ('should_come_num', models.IntegerField(verbose_name='应到人数')),
                ('absentee', models.CharField(blank=True, max_length=128, verbose_name='缺席名单')),
                ('notice', models.CharField(blank=True, max_length=128, verbose_name='备注')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internal.ClassList', verbose_name='班次')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='internal.TeacherInfo', verbose_name='上课老师')),
            ],
            options={
                'verbose_name': '上课记录',
                'verbose_name_plural': '上课记录',
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程介绍', 'verbose_name_plural': '课程介绍'},
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='stu_id',
            field=internal.fields.IdField(default='000000', max_length=6, verbose_name='学号'),
        ),
    ]
