# Generated by Django 2.0.4 on 2018-05-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internal', '0005_teacherinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('notice', models.CharField(blank=True, max_length=128, verbose_name='备注')),
                ('file', models.FileField(upload_to='./upload', verbose_name='导入文件')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '文件上传记录',
                'verbose_name_plural': '文件上传记录',
            },
        ),
    ]
