# Generated by Django 2.0.4 on 2018-05-04 04:47

from django.db import migrations, models
import internal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0008_auto_20180504_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=18, verbose_name='家长电话'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='QQ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='stu_id',
            field=internal.fields.IdField(default='000000', max_length=6, unique=True, verbose_name='学号'),
        ),
    ]
