# Generated by Django 2.0.4 on 2018-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0010_auto_20180505_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='grade',
            field=models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '十年级'), (11, '十一年级'), (12, '十二年级')], null=True, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='是否缴费'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='source',
            field=models.CharField(choices=[('qq', 'qq群'), ('school', '学校转化'), ('ads', '广告'), ('agent', '招生代理'), ('others', '其他'), ('wanbao', '晚报'), ('qingnianbao', '青年报')], default='agent', max_length=32, verbose_name='来源'),
        ),
    ]
