# Generated by Django 2.0.4 on 2018-05-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0011_auto_20180505_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.SchoolInfo', verbose_name='学校'),
        ),
    ]
