# Generated by Django 2.0.4 on 2018-05-08 01:05

from django.db import migrations
import internal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0012_auto_20180508_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='stu_id',
            field=internal.fields.IdField(max_length=6, null=True, unique=True, verbose_name='学号'),
        ),
    ]
