# Generated by Django 2.0.4 on 2018-05-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0013_auto_20180508_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='join_date',
            field=models.DateField(verbose_name='登记日期'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('unregistered', '未报名'), ('booked', '已预订'), ('graduated', '已毕业')], max_length=64, verbose_name='状态'),
        ),
    ]
