# Generated by Django 2.0.4 on 2018-05-08 01:22

from django.db import migrations, models
import django.db.models.deletion
import internal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0014_auto_20180508_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.ClassList', verbose_name='班次'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='referee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.MarketerInfo', verbose_name='招生人'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='source',
            field=models.CharField(blank=True, choices=[('qq', 'qq群'), ('school', '学校转化'), ('ads', '广告'), ('agent', '招生代理'), ('others', '其他'), ('wanbao', '晚报'), ('qingnianbao', '青年报')], default='agent', max_length=32, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='stu_id',
            field=internal.fields.IdField(blank=True, max_length=6, null=True, unique=True, verbose_name='学号'),
        ),
    ]
