# Generated by Django 2.0.4 on 2018-05-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0015_auto_20180508_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='grade',
            field=models.IntegerField(choices=[(0, '未知'), (1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '七年级'), (8, '八年级'), (9, '九年级'), (10, '十年级'), (11, '十一年级'), (12, '十二年级')], default=0, null=True, verbose_name='年级'),
        ),
    ]
