# Generated by Django 2.0.4 on 2018-05-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0016_auto_20180508_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='qq',
            field=models.CharField(blank=True, max_length=64, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('unregistered', '未报名'), ('booked', '已预订'), ('graduated', '已毕业')], default='unregistered', max_length=64, verbose_name='状态'),
        ),
    ]
