# Generated by Django 2.0.4 on 2018-05-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0017_auto_20180508_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=18, unique=True, verbose_name='家长电话'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='source',
            field=models.CharField(blank=True, choices=[('qq', 'qq群'), ('ditui', '地推'), ('wechat', '微信'), ('school', '学校转化'), ('ads', '广告'), ('agent', '招生代理'), ('others', '其他'), ('wanbao', '晚报'), ('qingnianbao', '青年报')], max_length=32, verbose_name='来源'),
        ),
    ]
