# Generated by Django 2.0.4 on 2018-05-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0018_auto_20180509_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='male', max_length=8, verbose_name=' 性别'),
        ),
    ]
