# Generated by Django 2.0.4 on 2018-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0019_auto_20180509_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='家长电话'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('yishiting', '已试听'), ('unregistered', '未报名'), ('booked', '已预订'), ('graduated', '已毕业')], default='unregistered', max_length=64, verbose_name='状态'),
        ),
    ]
